// trains.js - Real Train Data from Göteborg Central Station (Not accurate)

const initialServiceData = [
    {
        id: 1,
        arrivalTrainNumber: '',
        departureTrainNumber: '3500',
        origin: '',
        destination: 'Alingsås',
        scheduledArrivalTime: '23:36',
        scheduledDepartureTime: '00:06',
        trackId: 1,
        subTrackIndex: 2,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 2,
        arrivalTrainNumber: '3501',
        departureTrainNumber: '3508',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '',
        scheduledDepartureTime: '',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 3,
        arrivalTrainNumber: '3505',
        departureTrainNumber: '3512',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '',
        scheduledDepartureTime: '',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 4,
        arrivalTrainNumber: '3591',
        departureTrainNumber: '3516',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '00:21',
        scheduledDepartureTime: '',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 5,
        arrivalTrainNumber: '',
        departureTrainNumber: '3538',
        origin: '',
        destination: 'Alingsås',
        scheduledArrivalTime: '09:00',
        scheduledDepartureTime: '09:30',
        trackId: 1,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 6,
        arrivalTrainNumber: '3535',
        departureTrainNumber: '3542',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '10:18',
        scheduledDepartureTime: '10:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 7,
        arrivalTrainNumber: '3537',
        departureTrainNumber: '3544',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '10:51',
        scheduledDepartureTime: '11:07',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 8,
        arrivalTrainNumber: '3539',
        departureTrainNumber: '3546',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '11:24',
        scheduledDepartureTime: '11:40',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 9,
        arrivalTrainNumber: '3541',
        departureTrainNumber: '3548',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '11:54',
        scheduledDepartureTime: '12:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 10,
        arrivalTrainNumber: '3543',
        departureTrainNumber: '3550',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '12:24',
        scheduledDepartureTime: '12:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 11,
        arrivalTrainNumber: '3545',
        departureTrainNumber: '3552',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '12:52',
        scheduledDepartureTime: '13:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 12,
        arrivalTrainNumber: '3547',
        departureTrainNumber: '3554',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '13:24',
        scheduledDepartureTime: '13:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 13,
        arrivalTrainNumber: '3549',
        departureTrainNumber: '3556',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '13:52',
        scheduledDepartureTime: '14:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 14,
        arrivalTrainNumber: '3551',
        departureTrainNumber: '3558',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '14:24',
        scheduledDepartureTime: '14:40',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 15,
        arrivalTrainNumber: '3553',
        departureTrainNumber: '3560',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '14:52',
        scheduledDepartureTime: '15:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 16,
        arrivalTrainNumber: '3555',
        departureTrainNumber: '3562',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '15:23',
        scheduledDepartureTime: '15:41',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 17,
        arrivalTrainNumber: '3557',
        departureTrainNumber: '3564',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '15:51',
        scheduledDepartureTime: '16:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 18,
        arrivalTrainNumber: '3559',
        departureTrainNumber: '3566',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '16:18',
        scheduledDepartureTime: '16:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 19,
        arrivalTrainNumber: '3561',
        departureTrainNumber: '3568',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '16:51',
        scheduledDepartureTime: '17:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 20,
        arrivalTrainNumber: '3563',
        departureTrainNumber: '3570',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '17:15',
        scheduledDepartureTime: '17:45',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 21,
        arrivalTrainNumber: '3567',
        departureTrainNumber: '3574',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '18:18',
        scheduledDepartureTime: '18:40',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 22,
        arrivalTrainNumber: '3569',
        departureTrainNumber: '3576',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '18:51',
        scheduledDepartureTime: '19:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 23,
        arrivalTrainNumber: '3571',
        departureTrainNumber: '3578',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '19:27',
        scheduledDepartureTime: '19:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 24,
        arrivalTrainNumber: '',
        departureTrainNumber: '3580',
        origin: '',
        destination: 'Alingsås',
        scheduledArrivalTime: '19:36',
        scheduledDepartureTime: '20:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 25,
        arrivalTrainNumber: '3575',
        departureTrainNumber: '3584',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '20:28',
        scheduledDepartureTime: '21:06',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 26,
        arrivalTrainNumber: '3579',
        departureTrainNumber: '3586',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '21:24',
        scheduledDepartureTime: '21:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 27,
        arrivalTrainNumber: '3581',
        departureTrainNumber: '3590',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '21:51',
        scheduledDepartureTime: '22:36',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 28,
        arrivalTrainNumber: '3587',
        departureTrainNumber: '13594',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '23:23',
        scheduledDepartureTime: '23:35',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 29,
        arrivalTrainNumber: '3585',
        departureTrainNumber: '',
        origin: 'Alingsås',
        destination: '',
        scheduledArrivalTime: '22:51',
        scheduledDepartureTime: '23:21',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 2 }
    },
    {
        id: 30,
        arrivalTrainNumber: '3491',
        departureTrainNumber: '',
        origin: 'Skövde C',
        destination: '',
        scheduledArrivalTime: '00:18',
        scheduledDepartureTime: '00:48',
        trackId: 1,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 2 }
    },
    {
        id: 31,
        arrivalTrainNumber: '3613',
        departureTrainNumber: '3624',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '04:22',
        scheduledDepartureTime: '06:19',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 32,
        arrivalTrainNumber: '3693',
        departureTrainNumber: '3636',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '00:33',
        scheduledDepartureTime: '09:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 33,
        arrivalTrainNumber: '3633',
        departureTrainNumber: '3640',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '09:33',
        scheduledDepartureTime: '10:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 34,
        arrivalTrainNumber: '3637',
        departureTrainNumber: '3644',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '',
        scheduledDepartureTime: '11:22',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 35,
        arrivalTrainNumber: '3641',
        departureTrainNumber: '3648',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '11:35',
        scheduledDepartureTime: '12:22',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 36,
        arrivalTrainNumber: '3645',
        departureTrainNumber: '3652',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '12:32',
        scheduledDepartureTime: '13:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 37,
        arrivalTrainNumber: '3649',
        departureTrainNumber: '3656',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '13:34',
        scheduledDepartureTime: '14:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 38,
        arrivalTrainNumber: '3653',
        departureTrainNumber: '3660',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '14:33',
        scheduledDepartureTime: '15:21',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 39,
        arrivalTrainNumber: '3657',
        departureTrainNumber: '3664',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '15:33',
        scheduledDepartureTime: '16:22',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 40,
        arrivalTrainNumber: '3661',
        departureTrainNumber: '3668',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '16:33',
        scheduledDepartureTime: '17:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 41,
        arrivalTrainNumber: '3665',
        departureTrainNumber: '3672',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '17:33',
        scheduledDepartureTime: '18:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 42,
        arrivalTrainNumber: '17367',
        departureTrainNumber: '3676',
        origin: 'Varberg',
        destination: 'Ängelholm',
        scheduledArrivalTime: '19:05',
        scheduledDepartureTime: '19:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 43,
        arrivalTrainNumber: '3673',
        departureTrainNumber: '17380',
        origin: 'Ängelholm',
        destination: 'Varberg',
        scheduledArrivalTime: '19:32',
        scheduledDepartureTime: '20:50',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 44,
        arrivalTrainNumber: '3681',
        departureTrainNumber: '3688',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '21:32',
        scheduledDepartureTime: '22:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 45,
        arrivalTrainNumber: '3669',
        departureTrainNumber: '3692',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '18:33',
        scheduledDepartureTime: '23:20',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 46,
        arrivalTrainNumber: '3689',
        departureTrainNumber: '',
        origin: 'Ängelholm',
        destination: '',
        scheduledArrivalTime: '23:33',
        scheduledDepartureTime: '00:03',
        trackId: 10,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 47,
        arrivalTrainNumber: '17399',
        departureTrainNumber: '3600',
        origin: 'Varberg',
        destination: 'Ängelholm',
        scheduledArrivalTime: '00:04',
        scheduledDepartureTime: '00:21',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 48,
        arrivalTrainNumber: '3795',
        departureTrainNumber: '3734',
        origin: 'Uddevalla',
        destination: 'Uddevalla',
        scheduledArrivalTime: '01:26',
        scheduledDepartureTime: '08:39',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 49,
        arrivalTrainNumber: '3735',
        departureTrainNumber: '7034',
        origin: 'Stenungsund',
        destination: 'Stockholm C',
        scheduledArrivalTime: '10:19',
        scheduledDepartureTime: '11:15',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 500,
        arrivalTrainNumber: '3709',
        departureTrainNumber: '3746',
        origin: 'Uddevalla',
        destination: 'Uddevalla',
        scheduledArrivalTime: '11:00',
        scheduledDepartureTime: '11:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 50,
        arrivalTrainNumber: '3739',
        departureTrainNumber: '3746',
        origin: 'Uddevalla',
        destination: 'Uddevalla',
        scheduledArrivalTime: '11:19',
        scheduledDepartureTime: '11:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 51,
        arrivalTrainNumber: '3743',
        departureTrainNumber: '13750',
        origin: 'Uddevalla',
        destination: 'Sandhem',
        scheduledArrivalTime: '12:17',
        scheduledDepartureTime: '12:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 52,
        arrivalTrainNumber: '17343',
        departureTrainNumber: '13758',
        origin: 'Varberg',
        destination: 'Sandhem',
        scheduledArrivalTime: '13:06',
        scheduledDepartureTime: '14:41',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 53,
        arrivalTrainNumber: '3755',
        departureTrainNumber: '3762',
        origin: 'Uddevalla',
        destination: 'Uddevalla',
        scheduledArrivalTime: '15:15',
        scheduledDepartureTime: '15:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 54,
        arrivalTrainNumber: '17355',
        departureTrainNumber: '17364',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '16:04',
        scheduledDepartureTime: '16:49',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 55,
        arrivalTrainNumber: '3731',
        departureTrainNumber: '13772',
        origin: 'Uddevalla',
        destination: 'Sandhem',
        scheduledArrivalTime: '09:15',
        scheduledDepartureTime: '18:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 56,
        arrivalTrainNumber: '3771',
        departureTrainNumber: '3778',
        origin: 'Sandhem',
        destination: 'Uddevalla',
        scheduledArrivalTime: '19:18',
        scheduledDepartureTime: '19:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 57,
        arrivalTrainNumber: '3677',
        departureTrainNumber: '3684',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '20:33',
        scheduledDepartureTime: '21:20',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 58,
        arrivalTrainNumber: '',
        departureTrainNumber: '3786',
        origin: '',
        destination: 'Stenungsund',
        scheduledArrivalTime: '21:10',
        scheduledDepartureTime: '21:40',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 59,
        arrivalTrainNumber: '17379',
        departureTrainNumber: '17388',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '22:05',
        scheduledDepartureTime: '22:50',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 60,
        arrivalTrainNumber: '3787',
        departureTrainNumber: '17396',
        origin: 'Uddevalla',
        destination: 'Varberg',
        scheduledArrivalTime: '23:16',
        scheduledDepartureTime: '23:50',
        trackId: 11,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 61,
        arrivalTrainNumber: '3435',
        departureTrainNumber: '13742',
        origin: 'Trollhättan C',
        destination: 'Sandhem',
        scheduledArrivalTime: '09:59',
        scheduledDepartureTime: '10:43',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 62,
        arrivalTrainNumber: '3747',
        departureTrainNumber: '3754',
        origin: 'Sandhem',
        destination: 'Uddevalla',
        scheduledArrivalTime: '13:24',
        scheduledDepartureTime: '13:39',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 63,
        arrivalTrainNumber: '3751',
        departureTrainNumber: '3766',
        origin: 'Uddevalla',
        destination: 'Sandhem',
        scheduledArrivalTime: '14:18',
        scheduledDepartureTime: '16:40',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 64,
        arrivalTrainNumber: '23963',
        departureTrainNumber: '3770',
        origin: 'Sandhem',
        destination: 'Uddevalla',
        scheduledArrivalTime: '17:19',
        scheduledDepartureTime: '17:40',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 65,
        arrivalTrainNumber: '3775',
        departureTrainNumber: '3782',
        origin: 'Uddevalla',
        destination: 'Uddevalla',
        scheduledArrivalTime: '20:17',
        scheduledDepartureTime: '20:44',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 66,
        arrivalTrainNumber: '13779',
        departureTrainNumber: '3492',
        origin: 'Sandhem',
        destination: 'Skövde C',
        scheduledArrivalTime: '21:17',
        scheduledDepartureTime: '23:04',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 67,
        arrivalTrainNumber: '10483',
        departureTrainNumber: '3794',
        origin: 'Malmö C',
        destination: 'Uddevalla',
        scheduledArrivalTime: '11:40',
        scheduledDepartureTime: '23:39',
        trackId: 12,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 68,
        arrivalTrainNumber: '',
        departureTrainNumber: '20356',
        origin: '',
        destination: 'Kristianstad C',
        scheduledArrivalTime: '08:46',
        scheduledDepartureTime: '09:16',
        trackId: 13,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 69,
        arrivalTrainNumber: '',
        departureTrainNumber: '3043',
        origin: '',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '10:15',
        scheduledDepartureTime: '10:45',
        trackId: 13,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 70,
        arrivalTrainNumber: '20367',
        departureTrainNumber: '20372',
        origin: 'Kristianstad C',
        destination: 'Hässleholm',
        scheduledArrivalTime: '16:36',
        scheduledDepartureTime: '17:15',
        trackId: 13,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 71,
        arrivalTrainNumber: '13287',
        departureTrainNumber: '',
        origin: 'Sölvesborg',
        destination: '',
        scheduledArrivalTime: '12:45',
        scheduledDepartureTime: '13:15',
        trackId: 13,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 72,
        arrivalTrainNumber: '3000',
        departureTrainNumber: '3005',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '00:49',
        scheduledDepartureTime: '01:15',
        trackId: 14,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 73,
        arrivalTrainNumber: '',
        departureTrainNumber: '3039',
        origin: '',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '09:15',
        scheduledDepartureTime: '09:45',
        trackId: 14,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 74,
        arrivalTrainNumber: '3082',
        departureTrainNumber: '3087',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '21:14',
        scheduledDepartureTime: '21:45',
        trackId: 14,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 75,
        arrivalTrainNumber: '20337',
        departureTrainNumber: '',
        origin: 'Lund C',
        destination: '',
        scheduledArrivalTime: '16:55',
        scheduledDepartureTime: '17:25',
        trackId: 14,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 2 }
    },
    {
        id: 76,
        arrivalTrainNumber: '441',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '19:35',
        scheduledDepartureTime: '20:05',
        trackId: 14,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 2 }
    },
    {
        id: 77,
        arrivalTrainNumber: '3006',
        departureTrainNumber: '3013',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '02:15',
        scheduledDepartureTime: '03:21',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 78,
        arrivalTrainNumber: '3014',
        departureTrainNumber: '3025',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '04:21',
        scheduledDepartureTime: '06:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 79,
        arrivalTrainNumber: '3026',
        departureTrainNumber: '3033',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '07:14',
        scheduledDepartureTime: '08:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 80,
        arrivalTrainNumber: '3094',
        departureTrainNumber: '3037',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '00:16',
        scheduledDepartureTime: '09:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 81,
        arrivalTrainNumber: '3040',
        departureTrainNumber: '3045',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '10:44',
        scheduledDepartureTime: '11:16',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 82,
        arrivalTrainNumber: '3044',
        departureTrainNumber: '3049',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '11:43',
        scheduledDepartureTime: '12:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 83,
        arrivalTrainNumber: '3048',
        departureTrainNumber: '3053',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '12:44',
        scheduledDepartureTime: '13:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 84,
        arrivalTrainNumber: '3052',
        departureTrainNumber: '3057',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '13:45',
        scheduledDepartureTime: '14:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 85,
        arrivalTrainNumber: '3056',
        departureTrainNumber: '3061',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '14:49',
        scheduledDepartureTime: '15:15',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 86,
        arrivalTrainNumber: '3060',
        departureTrainNumber: '3065',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '15:45',
        scheduledDepartureTime: '16:16',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 87,
        arrivalTrainNumber: '3064',
        departureTrainNumber: '3069',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '16:47',
        scheduledDepartureTime: '17:16',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 88,
        arrivalTrainNumber: '3068',
        departureTrainNumber: '3073',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '17:45',
        scheduledDepartureTime: '18:17',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 89,
        arrivalTrainNumber: '3072',
        departureTrainNumber: '3077',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '18:44',
        scheduledDepartureTime: '19:16',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 90,
        arrivalTrainNumber: '3078',
        departureTrainNumber: '3083',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '20:18',
        scheduledDepartureTime: '20:45',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 91,
        arrivalTrainNumber: '3086',
        departureTrainNumber: '3091',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '22:15',
        scheduledDepartureTime: '22:45',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 92,
        arrivalTrainNumber: '3090',
        departureTrainNumber: '3095',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '23:16',
        scheduledDepartureTime: '23:45',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 93,
        arrivalTrainNumber: '3038',
        departureTrainNumber: '',
        origin: 'Kungsbacka',
        destination: '',
        scheduledArrivalTime: '10:17',
        scheduledDepartureTime: '10:47',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 94,
        arrivalTrainNumber: '3076',
        departureTrainNumber: '',
        origin: 'Kungsbacka',
        destination: '',
        scheduledArrivalTime: '',
        scheduledDepartureTime: '',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 95,
        arrivalTrainNumber: '17383',
        departureTrainNumber: '',
        origin: 'Varberg',
        destination: '',
        scheduledArrivalTime: '23:04',
        scheduledDepartureTime: '23:34',
        trackId: 15,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 96,
        arrivalTrainNumber: '',
        departureTrainNumber: '3001',
        origin: '',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '23:45',
        scheduledDepartureTime: '00:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 97,
        arrivalTrainNumber: '3002',
        departureTrainNumber: '3009',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '01:14',
        scheduledDepartureTime: '02:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 98,
        arrivalTrainNumber: '3010',
        departureTrainNumber: '3021',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '03:15',
        scheduledDepartureTime: '05:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 99,
        arrivalTrainNumber: '3022',
        departureTrainNumber: '3029',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '06:14',
        scheduledDepartureTime: '07:17',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 100,
        arrivalTrainNumber: '3030',
        departureTrainNumber: '3035',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '08:14',
        scheduledDepartureTime: '08:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 101,
        arrivalTrainNumber: '3036',
        departureTrainNumber: '3041',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '09:43',
        scheduledDepartureTime: '10:18',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 102,
        arrivalTrainNumber: '3042',
        departureTrainNumber: '3047',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '11:16',
        scheduledDepartureTime: '11:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 103,
        arrivalTrainNumber: '3046',
        departureTrainNumber: '3051',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '12:14',
        scheduledDepartureTime: '12:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 104,
        arrivalTrainNumber: '3050',
        departureTrainNumber: '3055',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '13:14',
        scheduledDepartureTime: '13:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 105,
        arrivalTrainNumber: '3054',
        departureTrainNumber: '3059',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '14:14',
        scheduledDepartureTime: '14:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 106,
        arrivalTrainNumber: '3058',
        departureTrainNumber: '3063',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '15:15',
        scheduledDepartureTime: '15:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 107,
        arrivalTrainNumber: '3062',
        departureTrainNumber: '3067',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '16:15',
        scheduledDepartureTime: '16:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 108,
        arrivalTrainNumber: '3066',
        departureTrainNumber: '3071',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '17:15',
        scheduledDepartureTime: '17:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 109,
        arrivalTrainNumber: '3070',
        departureTrainNumber: '3075',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '18:16',
        scheduledDepartureTime: '18:45',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 110,
        arrivalTrainNumber: '3074',
        departureTrainNumber: '3079',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '19:14',
        scheduledDepartureTime: '',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 111,
        arrivalTrainNumber: '3034',
        departureTrainNumber: '3081',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '09:13',
        scheduledDepartureTime: '20:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 112,
        arrivalTrainNumber: '3080',
        departureTrainNumber: '3085',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '20:44',
        scheduledDepartureTime: '21:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 113,
        arrivalTrainNumber: '3084',
        departureTrainNumber: '3089',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '21:45',
        scheduledDepartureTime: '22:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 114,
        arrivalTrainNumber: '3088',
        departureTrainNumber: '3093',
        origin: 'Kungsbacka',
        destination: 'Kungsbacka',
        scheduledArrivalTime: '22:44',
        scheduledDepartureTime: '23:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 115,
        arrivalTrainNumber: '3092',
        departureTrainNumber: '',
        origin: 'Kungsbacka',
        destination: '',
        scheduledArrivalTime: '23:45',
        scheduledDepartureTime: '00:15',
        trackId: 16,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 116,
        arrivalTrainNumber: '',
        departureTrainNumber: '3400',
        origin: '',
        destination: 'Skövde C',
        scheduledArrivalTime: '23:33',
        scheduledDepartureTime: '00:03',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 117,
        arrivalTrainNumber: '3593',
        departureTrainNumber: '3504',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '00:54',
        scheduledDepartureTime: '01:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 118,
        arrivalTrainNumber: '3513',
        departureTrainNumber: '3524',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '05:51',
        scheduledDepartureTime: '06:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 119,
        arrivalTrainNumber: '3521',
        departureTrainNumber: '3528',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '06:51',
        scheduledDepartureTime: '07:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 120,
        arrivalTrainNumber: '3525',
        departureTrainNumber: '3532',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '07:51',
        scheduledDepartureTime: '08:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 121,
        arrivalTrainNumber: '3529',
        departureTrainNumber: '3536',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '08:51',
        scheduledDepartureTime: '09:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "PENDELTAG", count: 1 }
    },
    {
        id: 122,
        arrivalTrainNumber: '3533',
        departureTrainNumber: '3540',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '09:51',
        scheduledDepartureTime: '10:08',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 123,
        arrivalTrainNumber: '3321',
        departureTrainNumber: '3322',
        origin: 'Mariestad',
        destination: 'Mariestad',
        scheduledArrivalTime: '11:07',
        scheduledDepartureTime: '11:31',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 124,
        arrivalTrainNumber: '385',
        departureTrainNumber: '388',
        origin: 'Oslo S',
        destination: 'Oslo S',
        scheduledArrivalTime: '11:43',
        scheduledDepartureTime: '12:15',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X403", count: 1 }
    },
    {
        id: 125,
        arrivalTrainNumber: '3323',
        departureTrainNumber: '3324',
        origin: 'Lidköping',
        destination: 'Mariestad',
        scheduledArrivalTime: '13:26',
        scheduledDepartureTime: '14:31',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 126,
        arrivalTrainNumber: '389',
        departureTrainNumber: '394',
        origin: 'Oslo S',
        destination: 'Oslo S',
        scheduledArrivalTime: '15:40',
        scheduledDepartureTime: '16:13',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 127,
        arrivalTrainNumber: '3325',
        departureTrainNumber: '3326',
        origin: 'Mariestad',
        destination: 'Mariestad',
        scheduledArrivalTime: '16:28',
        scheduledDepartureTime: '17:30',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 128,
        arrivalTrainNumber: '3565',
        departureTrainNumber: '3572',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '17:52',
        scheduledDepartureTime: '18:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 129,
        arrivalTrainNumber: '391',
        departureTrainNumber: '396',
        origin: 'Oslo S',
        destination: 'Oslo S',
        scheduledArrivalTime: '17:46',
        scheduledDepartureTime: '18:13',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 130,
        arrivalTrainNumber: '3327',
        departureTrainNumber: '3328',
        origin: 'Mariestad',
        destination: 'Lidköping',
        scheduledArrivalTime: '19:31',
        scheduledDepartureTime: '19:50',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 131,
        arrivalTrainNumber: '3573',
        departureTrainNumber: '3582',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '19:52',
        scheduledDepartureTime: '20:35',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 132,
        arrivalTrainNumber: '3577',
        departureTrainNumber: '3588',
        origin: 'Alingsås',
        destination: 'Alingsås',
        scheduledArrivalTime: '20:52',
        scheduledDepartureTime: '22:06',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 133,
        arrivalTrainNumber: '3469',
        departureTrainNumber: '',
        origin: 'Skövde C',
        destination: '',
        scheduledArrivalTime: '18:39',
        scheduledDepartureTime: '19:09',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 3 }
    },
    {
        id: 134,
        arrivalTrainNumber: '3583',
        departureTrainNumber: '',
        origin: 'Alingsås',
        destination: '',
        scheduledArrivalTime: '22:24',
        scheduledDepartureTime: '22:54',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 3 }
    },
    {
        id: 135,
        arrivalTrainNumber: '3589',
        departureTrainNumber: '',
        origin: 'Alingsås',
        destination: '',
        scheduledArrivalTime: '23:51',
        scheduledDepartureTime: '00:21',
        trackId: 2,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 3 }
    },
    {
        id: 136,
        arrivalTrainNumber: '',
        departureTrainNumber: '10480',
        origin: '',
        destination: 'Malmö C',
        scheduledArrivalTime: '05:10',
        scheduledDepartureTime: '05:40',
        trackId: 3,
        subTrackIndex: 2,
        trainSet: { vehicleTypeID: "SJ3000", count: 1 }
    },
    {
        id: 137,
        arrivalTrainNumber: '',
        departureTrainNumber: '2026',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '07:29',
        scheduledDepartureTime: '07:59',
        trackId: 3,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 138,
        arrivalTrainNumber: '3431',
        departureTrainNumber: '2030',
        origin: 'Skövde C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '08:53',
        scheduledDepartureTime: '09:59',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 139,
        arrivalTrainNumber: '',
        departureTrainNumber: '10434',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '11:49',
        scheduledDepartureTime: '12:19',
        trackId: 3,
        subTrackIndex: 3,
        trainSet: { vehicleTypeID: "SJ3000", count: 1 }
    },
    {
        id: 140,
        arrivalTrainNumber: '3453',
        departureTrainNumber: '2042',
        origin: 'Skövde C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '14:31',
        scheduledDepartureTime: '16:00',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 141,
        arrivalTrainNumber: '2029',
        departureTrainNumber: '3466',
        origin: 'Stockholm C',
        destination: 'Trollhättan C',
        scheduledArrivalTime: '13:58',
        scheduledDepartureTime: '16:30',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 142,
        arrivalTrainNumber: '173',
        departureTrainNumber: '188',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '16:57',
        scheduledDepartureTime: '18:02',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 143,
        arrivalTrainNumber: '435',
        departureTrainNumber: '446',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '16:33',
        scheduledDepartureTime: '18:24',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 144,
        arrivalTrainNumber: '439',
        departureTrainNumber: '3480',
        origin: 'Stockholm C',
        destination: 'Skövde C',
        scheduledArrivalTime: '18:27',
        scheduledDepartureTime: '20:03',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 145,
        arrivalTrainNumber: '',
        departureTrainNumber: '3484',
        origin: '',
        destination: 'Trollhättan C',
        scheduledArrivalTime: '20:35',
        scheduledDepartureTime: '21:05',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 146,
        arrivalTrainNumber: '445',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '21:27',
        scheduledDepartureTime: '21:57',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 147,
        arrivalTrainNumber: '20349',
        departureTrainNumber: '',
        origin: 'Lund C',
        destination: '',
        scheduledArrivalTime: '22:36',
        scheduledDepartureTime: '23:06',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 148,
        arrivalTrainNumber: '449',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '00:04',
        scheduledDepartureTime: '00:34',
        trackId: 3,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 149,
        arrivalTrainNumber: '',
        departureTrainNumber: '168',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '07:32',
        scheduledDepartureTime: '08:02',
        trackId: 4,
        subTrackIndex: 3,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 150,
        arrivalTrainNumber: '',
        departureTrainNumber: '426',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '07:49',
        scheduledDepartureTime: '08:19',
        trackId: 4,
        subTrackIndex: 2,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 151,
        arrivalTrainNumber: '',
        departureTrainNumber: '430',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '09:54',
        scheduledDepartureTime: '10:24',
        trackId: 4,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 152,
        arrivalTrainNumber: '',
        departureTrainNumber: '432',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '10:54',
        scheduledDepartureTime: '11:24',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 153,
        arrivalTrainNumber: '163',
        departureTrainNumber: '178',
        origin: 'Vårgårda',
        destination: 'Stockholm C',
        scheduledArrivalTime: '12:03',
        scheduledDepartureTime: '13:02',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 154,
        arrivalTrainNumber: '425',
        departureTrainNumber: '436',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '11:28',
        scheduledDepartureTime: '13:24',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 155,
        arrivalTrainNumber: '167',
        departureTrainNumber: '182',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '13:55',
        scheduledDepartureTime: '15:02',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 156,
        arrivalTrainNumber: '429',
        departureTrainNumber: '440',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '13:40',
        scheduledDepartureTime: '15:24',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 157,
        arrivalTrainNumber: '2033',
        departureTrainNumber: '2076',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '16:00',
        scheduledDepartureTime: '16:40',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 158,
        arrivalTrainNumber: '177',
        departureTrainNumber: '2050',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '18:54',
        scheduledDepartureTime: '19:59',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 159,
        arrivalTrainNumber: '2041',
        departureTrainNumber: '2092',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '20:02',
        scheduledDepartureTime: '21:18',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 160,
        arrivalTrainNumber: '2037',
        departureTrainNumber: '3488',
        origin: 'Stockholm C',
        destination: 'Skövde C',
        scheduledArrivalTime: '16:43',
        scheduledDepartureTime: '22:03',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 161,
        arrivalTrainNumber: '3685',
        departureTrainNumber: '3592',
        origin: 'Ängelholm',
        destination: 'Alingsås',
        scheduledArrivalTime: '22:33',
        scheduledDepartureTime: '23:06',
        trackId: 4,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 162,
        arrivalTrainNumber: '',
        departureTrainNumber: '170',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '08:38',
        scheduledDepartureTime: '09:08',
        trackId: 5,
        subTrackIndex: 2,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 163,
        arrivalTrainNumber: '',
        departureTrainNumber: '172',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '09:32',
        scheduledDepartureTime: '10:02',
        trackId: 5,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 164,
        arrivalTrainNumber: '53439',
        departureTrainNumber: '10490',
        origin: 'Skövde C',
        destination: 'Malmö C',
        scheduledArrivalTime: '10:54',
        scheduledDepartureTime: '11:54',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "SJ3000", count: 1 }
    },
    {
        id: 165,
        arrivalTrainNumber: '2025',
        departureTrainNumber: '2038',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '11:57',
        scheduledDepartureTime: '13:59',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 166,
        arrivalTrainNumber: '431',
        departureTrainNumber: '442',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '14:20',
        scheduledDepartureTime: '14:40',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 167,
        arrivalTrainNumber: '17363',
        departureTrainNumber: '17372',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '14:50',
        scheduledDepartureTime: '18:49',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 168,
        arrivalTrainNumber: '',
        departureTrainNumber: '3680',
        origin: '',
        destination: 'Ängelholm',
        scheduledArrivalTime: '19:52',
        scheduledDepartureTime: '20:22',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 169,
        arrivalTrainNumber: '181',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '21:05',
        scheduledDepartureTime: '21:35',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 2 }
    },
    {
        id: 170,
        arrivalTrainNumber: '447',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '22:39',
        scheduledDepartureTime: '23:09',
        trackId: 5,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 2 }
    },
    {
        id: 171,
        arrivalTrainNumber: '',
        departureTrainNumber: '428',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '08:48',
        scheduledDepartureTime: '09:18',
        trackId: 6,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 172,
        arrivalTrainNumber: '',
        departureTrainNumber: '174',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '10:32',
        scheduledDepartureTime: '11:02',
        trackId: 6,
        subTrackIndex: 3,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 173,
        arrivalTrainNumber: '',
        departureTrainNumber: '2034',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '11:29',
        scheduledDepartureTime: '11:59',
        trackId: 6,
        subTrackIndex: 2,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 174,
        arrivalTrainNumber: '165',
        departureTrainNumber: '180',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '12:54',
        scheduledDepartureTime: '14:02',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 175,
        arrivalTrainNumber: '427',
        departureTrainNumber: '438',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '12:33',
        scheduledDepartureTime: '14:24',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 176,
        arrivalTrainNumber: '20363',
        departureTrainNumber: '20368',
        origin: 'Hässleholm',
        destination: 'Kristianstad C',
        scheduledArrivalTime: '14:35',
        scheduledDepartureTime: '15:15',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 177,
        arrivalTrainNumber: '433',
        departureTrainNumber: '13216',
        origin: 'Stockholm C',
        destination: 'Sölvesborg',
        scheduledArrivalTime: '15:28',
        scheduledDepartureTime: '16:29',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 178,
        arrivalTrainNumber: '',
        departureTrainNumber: '444',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '16:49',
        scheduledDepartureTime: '17:19',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 179,
        arrivalTrainNumber: '175',
        departureTrainNumber: '450',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '17:55',
        scheduledDepartureTime: '20:20',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 180,
        arrivalTrainNumber: '2045',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '22:00',
        scheduledDepartureTime: '22:30',
        trackId: 6,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 181,
        arrivalTrainNumber: '',
        departureTrainNumber: '386',
        origin: '',
        destination: 'Oslo S',
        scheduledArrivalTime: '09:45',
        scheduledDepartureTime: '10:15',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X403", count: 1 }
    },
    {
        id: 182,
        arrivalTrainNumber: '',
        departureTrainNumber: '20330',
        origin: '',
        destination: 'Lund C',
        scheduledArrivalTime: '10:45',
        scheduledDepartureTime: '11:15',
        trackId: 7,
        subTrackIndex: 2,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 183,
        arrivalTrainNumber: '',
        departureTrainNumber: '176',
        origin: '',
        destination: 'Stockholm C',
        scheduledArrivalTime: '11:34',
        scheduledDepartureTime: '12:04',
        trackId: 7,
        subTrackIndex: 3,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 184,
        arrivalTrainNumber: '',
        departureTrainNumber: '3450',
        origin: '',
        destination: 'Skövde C',
        scheduledArrivalTime: '12:00',
        scheduledDepartureTime: '12:30',
        trackId: 7,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 185,
        arrivalTrainNumber: '387',
        departureTrainNumber: '390',
        origin: 'Oslo S',
        destination: 'Oslo S',
        scheduledArrivalTime: '13:43',
        scheduledDepartureTime: '14:15',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 186,
        arrivalTrainNumber: '169',
        departureTrainNumber: '184',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '14:56',
        scheduledDepartureTime: '16:00',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 187,
        arrivalTrainNumber: '20371',
        departureTrainNumber: '20376',
        origin: 'Kristianstad C',
        destination: 'Kristianstad C',
        scheduledArrivalTime: '18:34',
        scheduledDepartureTime: '19:15',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 188,
        arrivalTrainNumber: '395',
        departureTrainNumber: '398',
        origin: 'Oslo S',
        destination: 'Oslo S',
        scheduledArrivalTime: '19:44',
        scheduledDepartureTime: '20:09',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 189,
        arrivalTrainNumber: '437',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '17:27',
        scheduledDepartureTime: '17:57',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 190,
        arrivalTrainNumber: '20375',
        departureTrainNumber: '',
        origin: 'Kristianstad C',
        destination: '',
        scheduledArrivalTime: '20:42',
        scheduledDepartureTime: '21:12',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 191,
        arrivalTrainNumber: '397',
        departureTrainNumber: '',
        origin: 'Oslo S',
        destination: '',
        scheduledArrivalTime: '21:39',
        scheduledDepartureTime: '22:09',
        trackId: 7,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 192,
        arrivalTrainNumber: '20355',
        departureTrainNumber: '20364',
        origin: 'Kristianstad C',
        destination: 'Kristianstad C',
        scheduledArrivalTime: '10:37',
        scheduledDepartureTime: '13:14',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 193,
        arrivalTrainNumber: '',
        departureTrainNumber: '20338',
        origin: '',
        destination: 'Lund C',
        scheduledArrivalTime: '14:48',
        scheduledDepartureTime: '15:18',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 194,
        arrivalTrainNumber: '171',
        departureTrainNumber: '186',
        origin: 'Stockholm C',
        destination: 'Stockholm C',
        scheduledArrivalTime: '15:56',
        scheduledDepartureTime: '17:04',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 1 }
    },
    {
        id: 195,
        arrivalTrainNumber: '10489',
        departureTrainNumber: '10496',
        origin: 'Malmö C',
        destination: 'Malmö C',
        scheduledArrivalTime: '17:49',
        scheduledDepartureTime: '18:09',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "SJ3000", count: 1 }
    },
    {
        id: 196,
        arrivalTrainNumber: '3783',
        departureTrainNumber: '3790',
        origin: 'Uddevalla',
        destination: 'Stenungsund',
        scheduledArrivalTime: '22:18',
        scheduledDepartureTime: '22:40',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 197,
        arrivalTrainNumber: '179',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '20:08',
        scheduledDepartureTime: '20:38',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 198,
        arrivalTrainNumber: '11443',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '20:57',
        scheduledDepartureTime: '21:27',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 199,
        arrivalTrainNumber: '2047',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '22:56',
        scheduledDepartureTime: '23:26',
        trackId: 8,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 200,
        arrivalTrainNumber: '',
        departureTrainNumber: '3702',
        origin: '',
        destination: 'Uddevalla',
        scheduledArrivalTime: '00:10',
        scheduledDepartureTime: '00:40',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X40", count: 1 }
    },
    {
        id: 201,
        arrivalTrainNumber: '17391',
        departureTrainNumber: '17304',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '01:05',
        scheduledDepartureTime: '01:22',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 202,
        arrivalTrainNumber: '3603',
        departureTrainNumber: '17308',
        origin: 'Ängelholm',
        destination: 'Varberg',
        scheduledArrivalTime: '01:33',
        scheduledDepartureTime: '02:20',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 203,
        arrivalTrainNumber: '17303',
        departureTrainNumber: '17318',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '02:34',
        scheduledDepartureTime: '05:20',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 204,
        arrivalTrainNumber: '17317',
        departureTrainNumber: '17324',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '06:24',
        scheduledDepartureTime: '06:49',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 205,
        arrivalTrainNumber: '3625',
        departureTrainNumber: '3630',
        origin: 'Ängelholm',
        destination: 'Ängelholm',
        scheduledArrivalTime: '07:24',
        scheduledDepartureTime: '07:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 206,
        arrivalTrainNumber: '17323',
        departureTrainNumber: '17332',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '08:04',
        scheduledDepartureTime: '08:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 207,
        arrivalTrainNumber: '17327',
        departureTrainNumber: '17336',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '09:03',
        scheduledDepartureTime: '09:49',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 208,
        arrivalTrainNumber: '17331',
        departureTrainNumber: '17340',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '10:08',
        scheduledDepartureTime: '10:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 209,
        arrivalTrainNumber: '17335',
        departureTrainNumber: '17344',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '11:07',
        scheduledDepartureTime: '11:49',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 210,
        arrivalTrainNumber: '17339',
        departureTrainNumber: '17348',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '12:03',
        scheduledDepartureTime: '12:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 211,
        arrivalTrainNumber: '',
        departureTrainNumber: '17352',
        origin: '',
        destination: 'Varberg',
        scheduledArrivalTime: '13:20',
        scheduledDepartureTime: '13:50',
        trackId: 9,
        subTrackIndex: 1,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 212,
        arrivalTrainNumber: '17347',
        departureTrainNumber: '17356',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '14:04',
        scheduledDepartureTime: '14:49',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 213,
        arrivalTrainNumber: '17351',
        departureTrainNumber: '17360',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '15:04',
        scheduledDepartureTime: '15:49',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 214,
        arrivalTrainNumber: '17359',
        departureTrainNumber: '17368',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '17:03',
        scheduledDepartureTime: '17:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 215,
        arrivalTrainNumber: '3767',
        departureTrainNumber: '17376',
        origin: 'Uddevalla',
        destination: 'Varberg',
        scheduledArrivalTime: '18:18',
        scheduledDepartureTime: '19:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 216,
        arrivalTrainNumber: '17371',
        departureTrainNumber: '13236',
        origin: 'Varberg',
        destination: 'Sölvesborg',
        scheduledArrivalTime: '20:04',
        scheduledDepartureTime: '21:00',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "ORESUND", count: 1 }
    },
    {
        id: 217,
        arrivalTrainNumber: '17375',
        departureTrainNumber: '17384',
        origin: 'Varberg',
        destination: 'Varberg',
        scheduledArrivalTime: '21:04',
        scheduledDepartureTime: '21:50',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "REGINA", count: 1 }
    },
    {
        id: 218,
        arrivalTrainNumber: '3759',
        departureTrainNumber: '',
        origin: 'Uddevalla',
        destination: '',
        scheduledArrivalTime: '16:21',
        scheduledDepartureTime: '16:51',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 219,
        arrivalTrainNumber: '183',
        departureTrainNumber: '',
        origin: 'Stockholm C',
        destination: '',
        scheduledArrivalTime: '21:54',
        scheduledDepartureTime: '22:24',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    },
    {
        id: 220,
        arrivalTrainNumber: '10495',
        departureTrainNumber: '',
        origin: 'Malmö C',
        destination: '',
        scheduledArrivalTime: '23:29',
        scheduledDepartureTime: '23:59',
        trackId: 9,
        subTrackIndex: 0,
        trainSet: { vehicleTypeID: "X2", count: 3 }
    }
];

// Legacy support - for backwards compatibility
const initialTrainData = initialServiceData;

